language: node_js
node_js: 12
services:
  - docker
script:
- npm run codecov

cache:
  directories:
  - node_modules

env:
  global:
  - BX_APP=tone-analyzer-demo
  - BX_API=https://api.ng.bluemix.net
  - BX_ORGANIZATION=WatsonPlatformServices
  - BX_SPACE=demos
before_deploy:
  - docker build -t ibmwatson/tone-analyzer-nodejs .
  - npm install -g bx-blue-green
deploy:
- provider: script
  script: bx-blue-green-travis
  on:
    branch: master
    repo: watson-developer-cloud/tone-analyzer-nodejs
  skip_cleanup: true
- provider: script
  skip_cleanup: true
  script: npx semantic-release
